"""
Draft variant of functions_cycles.manipulation(): same period/frequency
model (average distance between historical tops), but the wave itself is an
asymmetric ("skewed") curve instead of a plain sine.

Why: with a plain sine, the bull leg (bottom -> top) and bear leg
(top -> bottom) are forced to be exactly half the cycle each. Historically
they aren't - BTC spends roughly 3/4 of a cycle climbing from bottom to top
and only ~1/4 falling back to the next bottom. The old sine's *maximum*
already lined up well with real tops, but its *minimum* landed about two
years after the real bottoms (bottoms actually line up with the sine's 75%
zero-crossing, not its literal trough).

This module keeps the exact same period/phase reference (so the wave's
maximum still falls where it already lined up with real tops) and reshapes
the curve so its *minimum* now falls where real bottoms already line up too
- while staying perfectly smooth (built from two cosine arcs joined at their
flat, zero-slope points, so there is no kink at the top or the bottom).

Everything else - plotting, annotations, colors, layout - is untouched and
reused as-is from functions_cycles. Only manipulation() is replaced.
"""

from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import numpy as np
import pandas as pd
from matplotlib.collections import LineCollection
from matplotlib.colors import Normalize
from matplotlib.ticker import ScalarFormatter
from datetime import datetime

from .functions_cycles import add_annotations_with_dates, calculate_cycle_percentage

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def _skewed_wave(psi: np.ndarray, rise_frac: float = 0.75) -> np.ndarray:
    """
    Asymmetric periodic wave in [-1, 1], parameterized by psi in [0, 1):
      - psi = 0          -> -1 (bottom)
      - psi = rise_frac  -> +1 (top)
      - psi = 1 (= 0 of the next cycle) -> -1 (next bottom)

    Built from two cosine arcs (rise_frac of the cycle rising, 1-rise_frac
    falling) joined where both arcs have zero slope - so the combined curve
    is smooth (no kink) at every top and bottom, just like a real sine.
    """
    psi = np.mod(psi, 1.0)
    fall_frac = 1.0 - rise_frac
    rising = psi < rise_frac

    wave = np.empty_like(psi, dtype=float)
    wave[rising] = -np.cos(np.pi * psi[rising] / rise_frac)
    wave[~rising] = np.cos(np.pi * (psi[~rising] - rise_frac) / fall_frac)
    return wave


def manipulation_asym(btc_data, tops_dates, rise_frac: float = 0.75):
    """
    Same signature/outputs as functions_cycles.manipulation(), except
    cycle_wave is generated by _skewed_wave() instead of np.sin(). All the
    downstream values (sin_maxima, sin_minima, sin_derivative,
    zero_crossings, current) are recomputed generically off the actual
    cycle_wave array - exactly like the original - so every plot annotation
    stays self-consistent with the new curve's real shape.

    Parameters:
    - btc_data: DataFrame with a 'time' column
    - tops_dates: datetime array of historical cycle tops
    - rise_frac: fraction of the cycle spent rising bottom -> top
      (default 0.75, i.e. a ~3-years-up / ~1-year-down cycle)
    """
    average_peak_distance = np.mean(
        np.diff(tops_dates).astype("timedelta64[D]").astype(int)
    )
    frequence_between_peaks = 1 / average_peak_distance

    # extended 6 months past the last confirmed top, same as functions_cycles
    cycle_dates = pd.date_range(start=btc_data["time"].min(), end="2027-01-31")

    # raw_cycles = number of full periods elapsed since the data start, using
    # the exact same period/phase reference as the original sine model
    raw_cycles = frequence_between_peaks * (cycle_dates - cycle_dates[0]).days
    # psi=0 anchored at the same real-world moment that already lined up with
    # historical bottoms in the old model (its 75%-phase zero-crossing)
    psi = np.mod(raw_cycles - 0.5, 1.0)
    cycle_wave = _skewed_wave(psi, rise_frac=rise_frac)

    next_peak_prediction_lower = tops_dates[-1] + pd.to_timedelta(
        np.diff(tops_dates).astype("timedelta64[D]").astype(int)[1], "D"
    )
    next_peak_prediction = tops_dates[-1] + pd.to_timedelta(average_peak_distance, "D")
    next_peak_prediction_upper = tops_dates[-1] + pd.to_timedelta(
        np.diff(tops_dates).astype("timedelta64[D]").astype(int)[0], "D"
    )

    sin_maxima = (
        np.where(
            (cycle_wave[:-2] < cycle_wave[1:-1]) & (cycle_wave[1:-1] > cycle_wave[2:])
        )[0]
        + 1
    )
    sin_minima = (
        np.where(
            (cycle_wave[:-2] > cycle_wave[1:-1]) & (cycle_wave[1:-1] < cycle_wave[2:])
        )[0]
        + 1
    )
    sin_derivative = np.gradient(cycle_wave, axis=0)
    zero_crossings = np.where(np.diff(np.sign(cycle_wave)))[0]
    current = calculate_cycle_percentage(btc_data, cycle_dates, sin_minima, sin_maxima)

    return (
        cycle_dates,
        cycle_wave,
        next_peak_prediction_lower,
        next_peak_prediction_upper,
        next_peak_prediction,
        sin_derivative,
        zero_crossings,
        current,
        sin_maxima,
        sin_minima,
    )


def cycle_annotation_phase_asym(
    ax1,
    ax2,
    fig,
    cycle_dates,
    sin_minima,
    halving_dates,
    tops_dates,
    bottoms_dates,
):
    """
    Same axis setup as functions_cycles.cycle_annotation_phase() (limits,
    tick formatting, halving/top/bottom vlines, "Cycle N" labels) - but the
    phase text is different: instead of the symmetric-wave's "0%/25%/50%/75%"
    (stale now that the wave itself is asymmetric), each cycle is split into
    4 equal time steps labeled 1, 2, 3, 4. By construction (rise_frac=0.75)
    marker 3 always lands exactly on the top and marker 4 always lands
    exactly on the bottom - making the fixed cadence explicit.
    """
    valid_minima = [i for i in sin_minima if cycle_dates[i] >= pd.to_datetime("2012-01-01")]

    # Fixed label heights, analytically known and constant every cycle (by
    # construction of the wave, not looked up per-instance): step 1 sits at
    # wave value -0.5, step 2 at +0.5, step 3 always at the top (~+1), step 4
    # always at the bottom (~-1). Kept well inside the y-limits (-1.02..1.05)
    # so the numbers never collide with the year tick labels below the axis.
    step_label_y = {1: -0.40, 2: 0.60, 3: 0.80, 4: -0.90}

    # mark every bottom (each cycle's start) with "4" - the vline itself is
    # drawn further below, together with bottoms_dates, in blue
    for idx in valid_minima:
        ax2.text(
            cycle_dates[idx],
            step_label_y[4],
            "4",
            color="b",
            fontsize=10,
            ha="center",
            va="bottom",
            fontweight="bold",
        )

    # split each bottom-to-bottom span into 4 equal time steps: 1, 2, 3 -
    # including the very first (partial) cycle, before the earliest detected
    # minimum, extrapolated backward using the same constant period (the wave
    # is built from a single fixed period throughout, so this is exact, not
    # a guess) so cycle 1's climb gets labeled too, not just cycles 2+
    period_days = int(
        round(np.mean(np.diff(tops_dates).astype("timedelta64[D]").astype(int)))
    )
    starts = (
        [valid_minima[0] - period_days] + valid_minima[:-1] if valid_minima else []
    )
    for i0, i1 in zip(starts, valid_minima):
        for k in (1, 2, 3):
            step_idx = i0 + round(period_days * k / 4)
            if not (0 <= step_idx < len(cycle_dates)):
                continue
            if cycle_dates[step_idx] < pd.to_datetime("2012-01-01"):
                continue
            ax2.text(
                cycle_dates[step_idx],
                step_label_y[k],
                str(k),
                color="b",
                fontsize=10,
                ha="center",
                va="bottom",
                fontweight="bold",
            )

    ax2.set_xlim(pd.to_datetime("2012-01-01"), cycle_dates[-1])
    ax1.set_ylim(3, 150_000)
    ax2.set_ylim(-1.02, 1.05)
    ax2.set_ylabel("Cycles", fontsize=13)
    ax2.tick_params(axis="y", which="both", left=False, labelleft=False)
    ax2.xaxis.set_major_locator(mdates.YearLocator())
    ax2.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
    fig.autofmt_xdate()

    for date in halving_dates:
        ax2.axvline(date, color="orange", linestyle="--", alpha=0.2)
    for date in tops_dates:
        ax2.axvline(date, color="green", linestyle="--", alpha=0.5)
    # bottoms (= cycle starts) in blue and thicker, standing in for the
    # separate cycle-start line - one line doing both jobs instead of two
    for date in bottoms_dates:
        ax2.axvline(date, color="blue", linestyle="--", linewidth=2.2, alpha=0.6)

    # "Cycle N" centered between one blue line (cycle start) and the next -
    # reuses the same (starts, valid_minima) pairing as the quarter-step
    # labels above, so it lines up with the same blue boundaries on screen
    cycle_labels = ["Cycle 1", "Cycle 2", "Cycle 3", "Cycle 4"]
    for i, (i0, i1) in enumerate(zip(starts, valid_minima)):
        mid_idx = min(max((i0 + i1) // 2, 0), len(cycle_dates) - 1)
        ax2.text(
            cycle_dates[mid_idx],
            -0.95,
            cycle_labels[i] if i < len(cycle_labels) else f"Cycle {i+1}",
            color="b",
            fontsize=13,
            ha="center",
            fontweight="bold",
        )


def plot_bitcoin_cycles_asym(
    btc_data,
    halving_dates,
    tops_dates,
    bottoms_dates,
    next_peak_prediction,
    next_peak_prediction_lower,
    next_peak_prediction_upper,
    cycle_dates,
    cycle_wave,
    sin_derivative,
    zero_crossings,
    sin_minima,
    sin_maxima,
    current,
):
    """
    Identical to functions_cycles.plot_bitcoin_cycles() - same layout,
    annotations, colors - reusing add_annotations_with_dates() and
    cycle_annotation_phase() as-is. The only difference is where it saves:
    output/2a.Cycles_AsymmetricWave.jpg and data/cycles_asym.csv, so this
    draft never overwrites the original notebook's output/2a.Cycles.jpg or
    data/cycles.csv.
    """
    fig = plt.figure(figsize=(14, 8))

    ax1 = fig.add_axes([0.05, 0.32, 0.93, 0.63])
    ax2 = fig.add_axes([0.05, 0.05, 0.93, 0.25], sharex=ax1)

    ax1.plot(btc_data["time"], btc_data["PriceUSD"], color="k", label="BTC Price USD")
    ax1.set_yscale("log")
    ax1.set_ylabel("Price USD", fontsize=13)
    ax1.set_title(
        "Bitcoin Cycles",
        fontsize=25,
        fontweight="bold",
    )
    ax1.tick_params(labelbottom=False)
    ax1.grid(axis="y", ls="--", alpha=0.4)

    ax1.yaxis.set_major_formatter(ScalarFormatter(useMathText=True))

    add_annotations_with_dates(ax1, halving_dates, "HALVING", "orange", 0.2)
    add_annotations_with_dates(ax1, tops_dates, "TOP", "green", 0.5)
    add_annotations_with_dates(ax1, bottoms_dates, "BOTTOM", "red", 0.5)

    # Unlike the symmetric-wave model (where a zero-crossing was the closest
    # proxy for "bottom", since the sine's own minimum landed ~2 years too
    # late), this wave's own minimum *is* the bottom by construction - so the
    # next bottom estimate is simply the first future entry in sin_minima.
    future_minima = [i for i in sin_minima if cycle_dates[i] > tops_dates[-1]]
    next_bottom_estimate = cycle_dates[future_minima[0]] if future_minima else None
    if next_bottom_estimate is not None:
        add_annotations_with_dates(
            ax1, [next_bottom_estimate], "NEXT BOTTOM (est.)", "red", 0.8
        )

    img_path = "../utils/btc_logo.png"
    img = plt.imread(img_path)
    left, width = 0.004, 0.2
    bottom, height = 0.88, 0.094
    right = left + width
    top = bottom + height
    ax1.imshow(
        img,
        aspect="auto",
        extent=[left, right, bottom, top],
        transform=ax1.transAxes,
        zorder=-1,
    )

    ax1.text(
        datetime(2012, 3, 1),
        18_000,
        f"Current cycle position: {current}",
        fontsize=10,
        va="top",
        ha="left",
        bbox=dict(facecolor="white"),
    )

    points = np.array([mdates.date2num(cycle_dates), cycle_wave]).T.reshape(-1, 1, 2)
    segments = np.concatenate([points[:-1], points[1:]], axis=1)

    colors = []
    norm = Normalize(vmin=np.min(cycle_wave), vmax=np.max(cycle_wave))
    cmap = plt.get_cmap("RdYlGn")

    for i in range(len(segments)):
        if i in sin_maxima:
            colors.append("green")
        elif i in zero_crossings and sin_derivative[i] < 0:
            colors.append("red")
        else:
            val = norm(cycle_wave[i])
            colors.append(cmap(val))

    lc = LineCollection(segments, colors=colors, linewidth=4)
    ax2.add_collection(lc)
    ax2.autoscale_view()

    for i in range(len(tops_dates)):
        if i < len(bottoms_dates):
            minima_indices = np.where(
                (cycle_dates > tops_dates[i]) & (cycle_dates < bottoms_dates[i])
            )[0]
            ax2.fill_between(
                x=cycle_dates[minima_indices],
                y1=-1.02,
                y2=1.05,
                color=(1, 0, 0, 0.15),
            )

    ax2.fill_between(
        x=cycle_dates[cycle_dates < tops_dates[0]],
        y1=-1.02,
        y2=1.05,
        color="green",
        alpha=0.15,
    )
    for i in range(len(bottoms_dates) - 1):
        minima_indices = np.where(
            (cycle_dates > bottoms_dates[i]) & (cycle_dates < tops_dates[i + 1])
        )[0]
        ax2.fill_between(
            x=cycle_dates[minima_indices],
            y1=-1.02,
            y2=1.05,
            color="green",
            alpha=0.15,
        )

    last_bottom = bottoms_dates[-1]
    last_top = tops_dates[-1]
    green_idx = (cycle_dates > last_bottom) & (cycle_dates <= last_top)
    ax2.fill_between(
        x=cycle_dates[green_idx],
        y1=-1.02,
        y2=1.05,
        color="green",
        alpha=0.15,
    )
    last_date = cycle_dates[-1]
    red_start = last_top
    red_idx = (cycle_dates > red_start) & (cycle_dates <= last_date)
    ax2.fill_between(
        x=cycle_dates[red_idx],
        y1=-1.02,
        y2=1.05,
        color=(1, 0, 0, 0.15),
    )

    cycle_annotation_phase_asym(
        ax1,
        ax2,
        fig,
        cycle_dates,
        sin_minima,
        halving_dates,
        tops_dates,
        bottoms_dates,
    )
    if next_bottom_estimate is not None:
        ax2.axvline(next_bottom_estimate, color="blue", linestyle="--", linewidth=2.2, alpha=0.7)
    ax1.text(
        btc_data.time.iloc[2800],
        100,
        "@Daniele Raimondi",
        fontsize=25,
        color="grey",
        alpha=0.25,
    )

    # export csv data for cycles - separate file, doesn't touch data/cycles.csv
    cycles_df = pd.DataFrame({"time": cycle_dates, "cycle": cycle_wave})
    cycles_df.to_csv(PROJECT_ROOT / "data" / "cycles_asym.csv", index=False)

    # Save the figure and display it - separate file, doesn't touch
    # output/2a.Cycles.jpg
    plt.savefig("../output/2a.Cycles_AsymmetricWave.jpg", dpi=400)
    plt.show()
